use_models:
  #Gradient Boosted Tree
  GB: true
  # logistic regression
  LR: true
  # Multinomial Naive Bayes
  NB: true
  # Random Forest Classifier
  RF: true
  # Linear Support Vector Classifier
  SVM: true

params:
  GB:
    ccp_alpha:
    - 0.0
    criterion:
    - friedman_mse
    init:
    - null
    learning_rate:
    - 0.1
    loss:
    - deviance
    max_depth:
    - 3
    max_features:
    - null
    max_leaf_nodes:
    - null
    min_impurity_decrease:
    - 0.0
    min_impurity_split:
    - null
    min_samples_leaf:
    - 1
    min_samples_split:
    - 2
    min_weight_fraction_leaf:
    - 0.0
    n_estimators:
    - 100
    n_iter_no_change:
    - null
    presort:
    - deprecated
    random_state:
    - null
    subsample:
    - 1.0
    tol:
    - 0.0001
    validation_fraction:
    - 0.1
    verbose:
    - 0
    warm_start:
    - false
  LR:
    C:
    - 1.0
    class_weight:
    - null
    dual:
    - false
    fit_intercept:
    - true
    intercept_scaling:
    - 1
    l1_ratio:
    - null
    max_iter:
    - 100
    multi_class:
    - auto
    n_jobs:
    - null
    penalty:
    - l2
    random_state:
    - null
    solver:
    - lbfgs
    tol:
    - 0.0001
    verbose:
    - 0
    warm_start:
    - false
  NB:
    alpha:
    - 1.0
    class_prior:
    - null
    fit_prior:
    - true
  RF:
    bootstrap:
    - true
    ccp_alpha:
    - 0.0
    class_weight:
    - null
    criterion:
    - gini
    max_depth:
    - null
    max_features:
    - auto
    max_leaf_nodes:
    - null
    max_samples:
    - null
    min_impurity_decrease:
    - 0.0
    min_impurity_split:
    - null
    min_samples_leaf:
    - 1
    min_samples_split:
    - 2
    min_weight_fraction_leaf:
    - 0.0
    n_estimators:
    - 100
    n_jobs:
    - null
    oob_score:
    - false
    random_state:
    - null
    verbose:
    - 0
    warm_start:
    - false
  SVM:
    C:
    - 1.0
    class_weight:
    - null
    dual:
    - true
    fit_intercept:
    - true
    intercept_scaling:
    - 1
    loss:
    - squared_hinge
    max_iter:
    - 1000
    multi_class:
    - ovr
    penalty:
    - l2
    random_state:
    - null
    tol:
    - 0.0001
    verbose:
    - 0
